/** Official Top 70 shortlist. Oct_ prefix kept only for Oct_SOLO teams. */
export const TOP70_TEAMS = [
  { name: "Kraken", university: "University of Moratuwa" },
  { name: "Oct_SOLO029", university: "University of Moratuwa" },
  { name: "Oct_SOLO060", university: "JIAT (Affiliated with IIC University)" },
  { name: "Triple I", university: "University of Kelaniya" },
  { name: "Oct_SOLO009", university: "Ruhuna" },
  { name: "Oct_SOLO077", university: "University of Moratuwa" },
  { name: "Quantum Minds", university: "University of Peradeniya" },
  { name: "Oct_SOLO004", university: "University of Kelaniya" },
  { name: "outlier protocol", university: "University of Moratuwa" },
  { name: "Code Mavericks", university: "University of Moratuwa" },
  { name: "Binary Belles", university: "IIT" },
  { name: "Knurdz Tenzr", university: "University of Moratuwa" },
  { name: "AlgoKnights", university: "SLIIT" },
  { name: "Prompt Addicts", university: "University of Moratuwa" },
  { name: "0110 0111", university: "University of Moratuwa" },
  { name: "Caffeine++", university: "University of Moratuwa" },
  { name: "Oct_SOLO005", university: "University of Moratuwa" },
  { name: "யாழி", university: "University of Peradeniya" },
  { name: "Endurance", university: "University of Moratuwa" },
  { name: "Oct_SOLO061", university: "University of Moratuwa" },
  { name: "ThinkSync", university: "University of Moratuwa" },
  { name: "Datoura", university: "University of Peradeniya" },
  { name: "Ionsplice", university: "University of Moratuwa" },
  { name: "TheByteForce", university: "University of Moratuwa" },
  { name: "ZeeBlitz", university: "NIBM" },
  { name: "Phantoms", university: "University of Moratuwa" },
  { name: "Data Alchemists", university: "University of Moratuwa" },
  { name: "Vector Minds", university: "University of Moratuwa" },
  { name: "Oct_SOLO071", university: "University of Moratuwa" },
  { name: "shogun", university: "University of Colombo" },
  { name: "Oct_SOLO083", university: "University of Moratuwa" },
  { name: "Phoenix", university: "University of Moratuwa" },
  { name: "Mora_vortex", university: "University of Moratuwa" },
  { name: "Blind Bandits", university: "University of Moratuwa" },
  { name: "GTricks", university: "University of Moratuwa" },
  { name: "Nova", university: "NIBM" },
  { name: "DelayedBoom", university: "University of Moratuwa" },
  { name: "BackTrack", university: "University of Moratuwa" },
  { name: "NeuraX", university: "University of Moratuwa" },
  { name: "Teal Titans", university: "University of Moratuwa" },
  { name: "Team Nova", university: "Ruhuna" },
  { name: "Gmora", university: "University of Moratuwa" },
  { name: "BigBug", university: "University of Moratuwa" },
  { name: "Neural surge", university: "University of Moratuwa" },
  { name: "Codestorm", university: "Sabaragamuwa University of Sri Lanka" },
  { name: "Mora Data Distillers", university: "University of Moratuwa" },
  { name: "Oct_SOLO013", university: "IIT" },
  { name: "Code Crusaders", university: "University of Moratuwa" },
  { name: "403Forbidden", university: "University of Moratuwa" },
  { name: "The hallucinators", university: "University of Moratuwa" },
  { name: "Prompt Pirates", university: "University of Moratuwa" },
  { name: "Neurons", university: "University of Moratuwa" },
  { name: "Encoders", university: "University of Moratuwa" },
  { name: "Shark Bytes", university: "University of Moratuwa" },
  { name: "NeuroKnights", university: "University of Peradeniya" },
  { name: "CogniVerse", university: "University of Moratuwa" },
  { name: "Axon", university: "University of Moratuwa" },
  { name: "Smile Labs", university: "University of Moratuwa" },
  { name: "Zenin", university: "University of Moratuwa" },
  { name: "Marster Coders", university: "Rajarata University of Sri Lanka" },
  { name: "Octabits", university: "University of Moratuwa" },
  { name: "InariCodeLabs", university: "NIBM" },
  { name: "Algostrom", university: "University of Moratuwa" },
  { name: "SpaceE", university: "Ruhuna" },
  { name: "Team Nexora", university: "University of Moratuwa" },
];
